import antfu from '@antfu/eslint-config'
// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(antfu({
  typescript: true,
  vue: true,
  // Extends antfu's default ignores (which already cover node_modules, dist,
  // lockfiles, etc.) and the parsed .gitignore. Only generated files that slip
  // through both need listing here.
  ignores: [
    'drizzle/**', // generated migration SQL + meta JSON
    'worker-configuration.d.ts', // generated by `wrangler types`
  ],
}))
