export const unitSymbolMap: { [key: string]: string } = {
  bag: "bag",
  box: "box",
  bunch: "bunch",
  can: "can",
  carton: "carton",
  centimeter: "cm",
  clove: "clove",
  container: "container",
  crown: "crown",
  cup: "cup",
  dash: "dash",
  drop: "drop",
  ear: "ear",
  "fluid ounce": "fl oz",
  foot: "ft",
  gallon: "gal",
  gram: "g",
  head: "head",
  inch: "in",
  kilogram: "kg",
  liter: "L",
  milligram: "mg",
  milliliter: "mL",
  ounce: "oz",
  pack: "pack",
  package: "pkg",
  piece: "piece",
  pinch: "pinch",
  pint: "pt",
  pound: "lb",
  quart: "qt",
  slice: "slice",
  stick: "stick",
  sprig: "sprig",
  tablespoon: "tbs",
  teaspoon: "tsp",

  small: "sm",
  medium: "med",
  large: "lg",
};
